global class CaseScheduler{
	/*
	public static final Integer START_MIN = 0;
	public static final Integer INTERVAL = 30;

	public static void scheduleJob() {
		for (Integer i = START_MIN; i < 60; i += INTERVAL) {
			string name = 'Case Scheduler - M' + String.valueOf(i).leftPad(2, '0');
			if (Test.isRunningTest()) { name += '_Test'; }
			System.schedule(name, '0 ' + i + ' * * * ? *', new CaseScheduler());
		}
	}

	public void execute(SchedulableContext ctx) {
		CaseCommon.schedule(datetime.now());
	}*/
	CaseScheduler(){
		
	}

}